/**
 * AuditEventType — local reflection-friendly copy. Mirrors the Prisma-generated
 * enum (same rationale as Role/TicketStatus: avoids SWC reflection issues).
 */
export enum AuditEventType {
  TICKET_ACKNOWLEDGED = 'TICKET_ACKNOWLEDGED',
  TICKET_STARTED = 'TICKET_STARTED',
  TICKET_ASSIGNED = 'TICKET_ASSIGNED',
  TICKET_ROUTED = 'TICKET_ROUTED',
  INFO_REQUESTED = 'INFO_REQUESTED',
  APPROVAL_REQUESTED = 'APPROVAL_REQUESTED',
  TICKET_APPROVED = 'TICKET_APPROVED',
  TICKET_RETURNED = 'TICKET_RETURNED',
  ESCALATION_TO_PS = 'ESCALATION_TO_PS',
  ESCALATION_TO_COMMISSIONER = 'ESCALATION_TO_COMMISSIONER',
  PS_DECISION = 'PS_DECISION',
  COMMISSIONER_DECISION = 'COMMISSIONER_DECISION',
  EXTERNAL_REFERRAL = 'EXTERNAL_REFERRAL',
  TICKET_RESOLVED = 'TICKET_RESOLVED',
  TICKET_CLOSED = 'TICKET_CLOSED',
  TICKET_AUTO_CLOSED = 'TICKET_AUTO_CLOSED',
  TICKET_REOPENED = 'TICKET_REOPENED',
  REOPEN_ESCALATION = 'REOPEN_ESCALATION',
  SLA_WARNING = 'SLA_WARNING',
  SLA_BREACH_ESCALATION = 'SLA_BREACH_ESCALATION',
  TICKET_TRIAGED = 'TICKET_TRIAGED',
  MINUTE_POSTED = 'MINUTE_POSTED',
  CITIZEN_INFO_REPLY = 'CITIZEN_INFO_REPLY',
  TICKET_ARCHIVED = 'TICKET_ARCHIVED',
}
